mqtt:
  host: localhost
  port: 1883
  topic_prefix: frigate
  client_id: frigate

detectors:
  coral:
    type: edgetpu
    device: pci

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://192.168.1.95:8554/cam
          roles:
            - detect
            - rtmp
    detect:
      enabled: True
    objects:
      track:
        - person
        - car
        - truck
        - motorcycle
        - bicycle
        - dog
        - cat
        - bird
